#!/bin/bash

# Ensure config directories exist
mkdir -p ~/.config/caelestia
mkdir -p ~/.config/quickshell/yoru

# Link shell.json config so caelestia reads the same config as yoru
if [ ! -L ~/.config/caelestia/shell.json ]; then
    ln -sfn ~/.config/quickshell/yoru/shell.json ~/.config/caelestia/shell.json 2>/dev/null
fi

# Link state directories so scheme.json generated by caelestia goes to yoru
if [ ! -L ~/.local/state/caelestia ]; then
    mkdir -p ~/.local/state/yoru
    ln -sfn ~/.local/state/yoru ~/.local/state/caelestia 2>/dev/null
fi

# Pass all arguments to caelestia CLI
exec caelestia "$@"
